<a href="https://colab.research.google.com/github/i1n2f3i4n5i6t7e8s9o10u11l/karthik/blob/main/20222.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


swapping two numbers in python

In [ ]:
# Second method of swapping
a = 3
b = 5
a,b = b,a
print(a)
print(b)

5
3


In [ ]:
a = 3
b = 5
a = a+b #8
b = a-b #3
a = a-b #5
print(a)
print(b)


5
3


A lambda function can take any number of arguments, but can only have one expression.



In [ ]:
x = lambda a, b : a * b
print(x(5, 6))

30



Global variables are those which are not defined inside any function and have a global scope


In [ ]:
def f():
    s += 'GFG'
    print("Inside Function", s)
  
  
# Global scope
s = "I love Geeksforgeeks"
f()

In [ ]:
local variables are those which are defined inside a function 

In [ ]:
def f():
  
    # local variable
    s = "I love Geeksforgeeks"
    print(s)
  
  
# Driver code
f()

print 1 to 5 numbers in python

In [ ]:
num = 1
while num < 6:
  print("num=", num)
  num = num + 1
else:
   print("loop is ended")


num= 1
num= 2
num= 3
num= 4
num= 5
loop is ended


In [ ]:
dist_1 = {'karthik':'nutan','are':'lovers'}


In [ ]:
print(dist_1)

{'karthik': 'nutan', 'are': 'lovers'}


python int

In [ ]:
# The number 2000 is an integer, we can confirm this by checking the type
type(2000)

int

In [ ]:
# The number -2000 is an integer, we can confirm this by checking the type
type(-2000)


int

In [ ]:
# A decimal number is of the type 'float' which is short for 'floating point number'
type(2.3)

float

Basic Arithmetic Operations and functions

In [ ]:
2+3

5

In [ ]:
2-3

-1

In [ ]:
2/3

0.6666666666666666

In [ ]:
2*3

6

In [ ]:
x = 1
y = 3
z = 10
x+y+z

14

In [ ]:
x+y+z

14

In [ ]:
x-y

-2

In [ ]:
2**(3+5)*3/2+2-1

385.0

Strings  ()



---



---



---


Strings are sequences of characters
Strings should be enclosed in:
•	Single quotes: 'This is a string'
•	Double quotes: "This is a string"
•	Triple quotes: '''This is a string''' and """This is also a string"""




---



In [ ]:
'This is a string'

'This is a string'

In [ ]:
"This is a string"

'This is a string'

In [ ]:
"""This is a string"""

'This is a string'

In [ ]:
# A number enclosed in quotes is also a string
type('2')

str

In [ ]:
# A number enclosed in quotes is also a string
type('-2')

str

In [ ]:
# A number enclosed in quotes is also a string
type("2")

str

In [ ]:
# A number enclosed in quotes is also a string
type("""2""")

str

In [ ]:
type('The student said "it is fun to learn Python"')

str

In [ ]:
type('The student said "it\'s fun to learn Python"')

str

\n = next line

In [ ]:
# The escape sequence '\n' prints the remaining text in a new line
print('hello I would like this \nstring in two lines')

hello I would like this 
string in two lines


\t = same line

In [ ]:
# The escape sequence '\t' prints the remaining text in a new line
print('hello I would like this \tstring in two lines')

hello I would like this 	string in two lines


*String Concatenation *

In [ ]:
x = 'My name'
y = 'joe'
x+y

'My namejoe'

In double *quotes*

In [ ]:
x = "My name"
y = "joe"
x+y

'My namejoe'

Lists [ ]



Lists The list is a sequence data type which is used to store the collection of data in squared brackets, lists are Not immutable

In [ ]:
x = 'Hello'
x[1]

'e'

In [ ]:
list_1 = [2,3,4,5,6,7]
list_2 = ['karthik','nutan','parents','bro']

In [ ]:
list_1

[2, 3, 4, 5, 6, 7]

In [ ]:
list_2

['karthik', 'nutan', 'parents', 'bro']

Dictionaries are used to store data values in key:value pairs.

1.  Dictionaries are ordered , mutable and do not allow duplicate objects








dict_1 = {'key':value1, 'key2':value2}

In [ ]:
dict_1 = {'karthik':'thop','nutan':'thop'}

In [ ]:
dict_1

{'karthik': 'thop', 'nutan': 'thop'}

Tuples  ( )  The tuples is a sequence data type which is used to store the collection of data in circle brackets, tuples are immutable


In [ ]:
x = (1,2,3)
x
type(x)

tuple

In [ ]:
x=(1,'John',[1,2,3],{'key1','value1'})
x
type(x)

tuple

**Sets**  { } Sets is an unordered collection of items and elements are immutable

In [ ]:
x = {1,2,3}
x
type(x)

set

Booleans
A boolean is a data type with two possible values:
•	True
•	False


In [ ]:
type(True)

bool

In [ ]:
type(False)

bool

In [ ]:
5>7

False

In [ ]:
5<7

True

In [ ]:
type(5>7)

bool

In [ ]:
type(5<7)

bool

Arithmetic Operators
+ Addition
- Subtraction
* Multiplication
/ Division
% Modulus
***Exponent



In [ ]:
a = 10
b = 20
a 

10

In [ ]:
a+b

30

In [ ]:
a-b

-10

In [ ]:
b-a

10

In [ ]:
10<20

True

In [ ]:
20>10

True

Logical Operators

In [ ]:
4>3

True

In [ ]:
100>3

True

In [ ]:
4>3 and 100>3

True

In [ ]:
3>1 and 3==3 and 4<100

True

In [ ]:
4<3

False

if elif else

In [ ]:
if 4>3:
   print('the condition is true')


the condition is true


if - else statement

In [ ]:
if 5<100:
  print('the if statement is true')
if 5<100:
   print('the second if statement is true')
if 5<100:
   print('the third if statement is true')

the if statement is true
the second if statement is true
the third if statement is true


Lists The list is a sequence data type which is used to store the collection of data in squared brackets, lists are Not immutable

In [ ]:
list_1 = [1,2,3,4]

In [ ]:
list_1

[1, 2, 3, 4]

In [ ]:
for x in list_1:
    print('1,2,3,4')

1,2,3,4
1,2,3,4
1,2,3,4
1,2,3,4
1,2,3,4


Tuples  

In [ ]:
tuple = ("karthik","nuthan","akshitha","ashmitha")
print(tuple)

('karthik', 'nuthan', 'akshitha', 'ashmitha')


while loop

In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


Built in functions in python


print( )

In [ ]:
print('hello')

hello


In [ ]:
print([1,2,3])

[1, 2, 3]


In [ ]:
print({'hgvh','xfhcgvjh','cgjv'})

{'xfhcgvjh', 'cgjv', 'hgvh'}


type( )

In [ ]:
type('hello world')

str

In [ ]:
type([1,2,3])

list

In [ ]:
type({'hgvh','xfhcgvjh','cgjv'})

set

numpy functions It is a Python library used for working with an array.


creating 1D array

In [ ]:
import numpy as np

In [ ]:
n = np.array([1,2,3])
n

array([1, 2, 3])

In [ ]:
type(n)

numpy.ndarray

2D array

In [ ]:
n = np.array([(1,2,3),(4,5,6)])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.shape(n)

(2, 3)

3D array

In [ ]:
n = np.array([(1,2,3),(4,5,6),(7,8,9)])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.shape(n)

(3, 3)

arange

In [ ]:
import numpy as np

In [ ]:
n = np.arange(100)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


printing ones

In [ ]:
n = np.ones(6)
n

array([1., 1., 1., 1., 1., 1.])

In [ ]:
n = np.ones((2,3,4))
n

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

identity matrics in numpy

In [ ]:
n = np.eye(3)
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

numpy.linspace( )is a function that is used for creating numeric sequences over a specified interval. 

In [ ]:
n = np.linspace(0,100,21)
n

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

The Python numpy random randint function returns or generates random integer values from the start (low) to the end (high).

In [ ]:
n = np.random.randint(0,1000,500)
n

array([829,  26, 913, 308, 347, 234, 145, 405, 877, 722, 742, 529, 476,
         8, 719, 882, 181, 563, 807,   4, 152, 361, 692, 537, 164, 976,
       877, 941, 517, 230, 453, 737, 938, 920, 718, 345, 728, 683, 109,
       529, 342, 644,  55, 431, 277, 749, 773, 827, 605, 540, 848, 949,
       156, 993,  80, 910, 926, 346, 651, 462, 825, 327, 480, 117, 697,
       680,  25, 675, 241, 100, 141, 312, 783,  42, 749, 252, 224, 333,
       663, 678, 512, 791,  69, 380, 737, 879, 796, 931, 871, 356, 879,
       475, 260, 875, 805, 173, 179,  34,  33, 576, 777, 213, 140, 269,
        98, 714, 200, 210, 238, 718, 829, 296,  64,  96, 439, 241, 240,
       649, 679, 988, 345, 740, 113,  24, 423, 275, 630, 312, 700, 511,
       518, 469, 828, 191, 849, 728, 498, 426, 500, 835, 385, 215, 467,
       952, 315, 106, 574, 933, 957, 669, 206, 276, 610, 893, 465, 156,
       265, 944, 553, 406, 839, 199, 129, 107, 817, 204, 888, 527, 186,
       106, 637, 939, 845, 166, 893, 138, 378, 913,  97, 993, 41

Reshaping arrays¶

In [ ]:
a = np.arange(100)
b = a.reshape(4,25)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


Create a 5 row by 3 column array that contains only the value 7

In [ ]:
np.full((5,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Array slicing and indexing in numpy

1D slicing

In [ ]:
array_1d = np.array([2,5,6,7,6,4,3])
array_2d = np.array([[2,5,6,7,60,47,3],[11,50,6,9,62,42,30],[16,53,86,69,2,2,50]]

In [ ]:
array_1d


array([2, 5, 6, 7, 6, 4, 3])

In [ ]:
array_2d


array([[ 2,  5,  6,  7, 60, 47,  3],
       [11, 50,  6,  9, 62, 42, 30],
       [16, 53, 86, 69,  2,  2, 50]])

2D slicing

In [ ]:
array_2d

array([[ 2,  5,  6,  7, 60, 47,  3],
       [11, 50,  6,  9, 62, 42, 30],
       [16, 53, 86, 69,  2,  2, 50]])


In [ ]:
array_2d[1:,2:]


array([[ 6,  9, 62, 42, 30],
       [86, 69,  2,  2, 50]])

Boolean Array Indexing

In [ ]:
array_1d

array([2, 5, 6, 7, 6, 4, 3])

In [ ]:
array_1d>3

array([False,  True,  True,  True,  True,  True, False])

In [ ]:
array_2d

array([[ 2,  5,  6,  7, 60, 47,  3],
       [11, 50,  6,  9, 62, 42, 30],
       [16, 53, 86, 69,  2,  2, 50]])

In [ ]:
array_2d>10

array([[False, False, False, False,  True,  True, False],
       [ True,  True, False, False,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True]])

PANDAS

pandas used to make dataframe, dataframes are more structurles forms


In [ ]:
import pandas as pd
row_labels = [0,1,2,3,4]
column_labels = ['A','B','C']
data = [[1,2,5],(4,2,4),{6,7,9},[3,2,4],[3,3,2]]

In [ ]:
df = pd.DataFrame(index=row_labels, data=data, columns=column_labels)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

A  B  C
0  1  2  5
1  4  2  4
2  9  6  7
3  3  2  4
4  3  3  2

df = pd.read_csv(" ") to read data 

In [ ]:
countries_table = pd.read_csv(filepath_or_buffer='top_10_countries.csv')

In [ ]:
coundries.head()

  Rank	Country / Dependency	Region	 Population	% of world	Date
0	1	        China 	          asia  1,412,600,000	17.80%	 31-Dec-21
1	2	         India		    Asia      1,386,946,912	 17.50%	   18-Jan-22
2	3	        United States	Americas	333,073,186  	4.20%	     18-Jan-22
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20

In [ ]:
type(countries_table)

pandas.core.frame.DataFrame

In [ ]:
# if header=None then column names will be generated using the 1 axis index positions
countries_table = pd.read_csv('top_10_countries_no_header.csv', header=None)

In [ ]:
countries_table

   0             1               2         3           4       5       
  Rank	Country / Dependency	Region	 Population	% of world	Date
0	1	        China 	          asia  1,412,600,000	17.80%	 31-Dec-21
1	2	         India		    Asia      1,386,946,912	 17.50%	   18-Jan-22
2	3	        United States	Americas	333,073,186  	4.20%	     18-Jan-22
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20

selecting data from data set

In [ ]:
import pandas as pd

In [ ]:
countries_data = pd.read_csv('top_10_countries.csv')

Selecing a single column

In [ ]:
countries_data

  Rank	Country / Dependency	Region	 Population	% of world	Date
0	1	        China 	          asia  1,412,600,000	17.80%	 31-Dec-21
1	2	         India		    Asia      1,386,946,912	 17.50%	   18-Jan-22
2	3	        United States	Americas	333,073,186  	4.20%	     18-Jan-22
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20


In [ ]:
# Selecing the 'Region' column
countries_data['Region']

0        Asia
1        Asia
2    Americas
3        Asia
4        Asia
5    Americas
6      Africa
7        Asia
8      Europe
9    Americas
Name: Region, dtype: object

In [ ]:
# A single column is a Series object - a DataFrame is a collection of Series objects
type(countries_data['Region'])


pandas.core.series.Series



Selecting multiple columns

In [ ]:
countries_data

countries_data
  Rank	Country / Dependency	Region	 Population	% of world	Date
0	1	        China 	          asia  1,412,600,000	17.80%	 31-Dec-21
1	2	         India		    Asia      1,386,946,912	 17.50%	   18-Jan-22
2	3	        United States	Americas	333,073,186  	4.20%	     18-Jan-22
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20

In [ ]:
# multiple columns must be passed into a list
countries_data[['Region','Country / Dependency', 'Rank']]

	Region	Country / Dependency	Rank
0	Asia	          China	         1
1	Asia	          India	         2
2	Americas	      United States	3
3	Asia	          Indonesia[b]	4
4	Asia	          Pakistan	    5
5	Americas	      Brazil	      6
6	Africa	        Nigeria	      7
7	Asia	          Bangladesh	  8
8	Europe	        Russia[b]	    9
9	Americas       	Mexico	      10


Selecting rows and columns¶

In [ ]:
countries_data
  Rank	Country / Dependency	Region	 Population	% of world	Date
0	1	        China 	          asia  1,412,600,000	17.80%	 31-Dec-21
1	2	         India		    Asia      1,386,946,912	 17.50%	   18-Jan-22
2	3	        United States	Americas	333,073,186  	4.20%	     18-Jan-22
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20



In [ ]:
# iloc requires index positions
countries_data.iloc[3]

Rank                              4
Country / Dependency     Indonesia[b]
Region                           Asia
Population                271350000.0
% of world                      3.42%
Date                        31-Dec-20
Name: 3, dtype: object


In [ ]:
# Slicing the rows
countries_data.iloc[3:]

 Rank	Country / Dependency	Region	 Population	% of world	Date
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20


In [ ]:
# Reversing the rows
countries_data.iloc[::-1]

  Rank	 Country / Dependency	Region	Population	% of world	Date
9	10	           Mexico	Americas	1.260140e+08	1.59%	02-Mar-20
8	9	         Russia[b]	Europe	1.461710e+08	1.84%	01-Jan-21
7	8	           Bangladesh	Asia	1.720626e+08	2.17%	18-Jan-22
6	7	           Nigeria	Africa	2.114010e+08	2.67%	01-Jul-21
5	6	           Brazil	Americas	2.142316e+08	2.70%	18-Jan-22
4	5           	Pakistan	Asia	2.252000e+08	2.84%	01-Jul-21
3	4	            Indonesia[b]	Asia	2.713500e+08	3.42%	31-Dec-20
2	3	           United States	Americas	3.330732e+08	4.20%	18-Jan-22
1	2         	India	Asia	1.386947e+09	17.50%	18-Jan-22
0	1	          China	Asia	1.412600e+09	17.80%	31-Dec-21


In [ ]:
countries_data
  Rank	Country / Dependency	Region	 Population	% of world	Date
0	1	        China 	          asia  1,412,600,000	17.80%	 31-Dec-21
1	2	         India		    Asia      1,386,946,912	 17.50%	   18-Jan-22
2	3	        United States	Americas	333,073,186  	4.20%	     18-Jan-22
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20


In [ ]:
# slicing rows and columns with loc requires label names
countries_data.loc[2:,['Country / Dependency','Population']]

	Country / Dependency	Population
2	United States	333073186.0
3	Indonesia[b]	271350000.0
4	Pakistan	225200000.0
5	Brazil	214231641.0
6	Nigeria	211401000.0
7	Bangladesh	172062576.0
8	Russia[b]	146171015.0
9	Mexico	126014024.0

Data manipulation

In [ ]:
import pandas as pd

In [ ]:
countries_df = pd.read_csv('top_10_countries.csv')

In [ ]:
countries_df.shape

(10, 6)

In [ ]:
# using the rename method to rename one of the columns
countries_df.rename(columns={'Country / Dependency': 'Country'}, inplace=True)

In [ ]:
countries_df

 Rank	     Country        Region	 Population	% of world	Date
0	1	        China 	      asia   1,412,600,000	17.80%	 31-Dec-21
1	2	         India		    Asia      1,386,946,912	 17.50%	   18-Jan-22
2	3	        United States	Americas	333,073,186  	4.20%	     18-Jan-22
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     31-Dec-20
4	5	       Pakistan		     Asia     225,200,000	  2.84%	     01-Jul-21
5	6	       Brazil		       Americas 14,231,641	  2.70%	     18-Jan-22
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     01-Jul-21
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	     18-Jan-22
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	     01-Jan-21
9	10      	Mexico       Americas 	126,014,024	  1.59%	     02-Mar-20




In [ ]:
# Using the drop method to drop the 'Date' columns
countries_df.drop(columns='Date', inplace=True)

countries_df


 Rank	     Country        Region	 Population	% of world
0	1	        China 	      asia   1,412,600,000	17.80%	 
1	2	         India		    Asia      1,386,946,912	 17.50%	   
2	3	        United States	Americas	333,073,186  	4.20%	     
3	4         Indonesia[b]	 Asia	    271,350,000	  3.42%	     
4	5	       Pakistan		     Asia     225,200,000	  2.84%	    
5	6	       Brazil		       Americas 14,231,641	  2.70%	     
6	7	       Nigeria	       	Africa 211,401,000	  2.67%	     
7	8	       Bangladesh		    Asia   172,062,576	  2.17%	    
8	9	         Russia[b]	  Europe    146,171,015	  1.84%	 
9	10      	Mexico       Americas 	126,014,024	  1.59%	    



drop column

In [ ]:
import pandas as pd
countries_df = pd.read_csv('top_10_countries.csv')
countries_df.drop(columns=['% of world','Date'],inplace=True)

rename column

In [ ]:
countries_df.rename(columns={'Country / Dependency':'Country'}, inplace=True)

two ways to handle missing values


what is data preprocessing

In [ ]:
# step 1 importing modules 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')

In [ ]:
dataset = pd.read_csv('WorldCupMatches.csv')

In [ ]:
dataset.head()

Year	Datetime	Stage	Stadium	City	Home Team Name	Home Team Goals	Away Team Goals	Away Team Name	Win conditions	Attendance	Half-time Home Goals	Half-time Away Goals	Referee	Assistant 1	Assistant 2	RoundID	MatchID	Home Team Initials	Away Team Initials
0	1930.0	13 Jul 1930 - 15:00	Group 1	Pocitos	Montevideo	France	4.0	1.0	Mexico		4444.0	3.0	0.0	LOMBARDI Domingo (URU)	CRISTOPHE Henry (BEL)	REGO Gilberto (BRA)	201.0	1096.0	FRA	MEX
1	1930.0	13 Jul 1930 - 15:00	Group 4	Parque Central	Montevideo	USA	3.0	0.0	Belgium		18346.0	2.0	0.0	MACIAS Jose (ARG)	MATEUCCI Francisco (URU)	WARNKEN Alberto (CHI)	201.0	1090.0	USA	BEL
2	1930.0	14 Jul 1930 - 12:45	Group 2	Parque Central	Montevideo	Yugoslavia	2.0	1.0	Brazil		24059.0	2.0	0.0	TEJADA Anibal (URU)	VALLARINO Ricardo (URU)	BALWAY Thomas (FRA)	201.0	1093.0	YUG	BRA
3	1930.0	14 Jul 1930 - 14:50	Group 3	Pocitos	Montevideo	Romania	3.0	1.0	Peru		2549.0	1.0	0.0	WARNKEN Alberto (CHI)	LANGENUS Jean (BEL)	MATEUCCI Francisco (URU)	201.0	1098.0	ROU	PER
4	1930.0	15 Jul 1930 - 16:00	Group 1	Parque Central	Montevideo	Argentina	1.0	0.0	France		23409.0	0.0	0.0	REGO Gilberto (BRA)	SAUCEDO Ulises (BOL)	RADULESCU Constantin (ROU)	201.0	1085.0	ARG	FRA



In [ ]:
dataset.shape
(4572, 20)

In [ ]:
dataset.tail()

      Year	Datetime	Stage	Stadium	City	Home Team Name	Home Team Goals	Away Team Goals	Away Team Name	Win conditions	Attendance	Half-time Home Goals	Half-time Away Goals	Referee	Assistant 1	Assistant 2	RoundID	MatchID	Home Team Initials	Away Team Initials
4567	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
4568	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
4569	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
4570	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
4571	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    object 
 2   Stage                 852 non-null    object 
 3   Stadium               852 non-null    object 
 4   City                  852 non-null    object 
 5   Home Team Name        852 non-null    object 
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    object 
 9   Win conditions        852 non-null    object 
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    object 
 14  Assistant 1           852 non-null    object 
 15  Assistant 2           852 non-null    object 
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    object 
 19  Away Team Initials    852 non-null    object 
dtypes: float64(8), object(12)
memory usage: 714.5+ KB

In [ ]:
dataset.describe()

        Year	Home Team Goals	Away Team Goals	Attendance	Half-time Home Goals	Half-time Away Goals	RoundID	MatchID
count	852.000000	852.000000	852.000000	850.000000	852.000000	852.000000	8.520000e+02	8.520000e+02
mean	1985.089202	1.811033	1.022300	45164.800000	0.708920	0.428404	1.066177e+07	6.134687e+07
std	22.448825	1.610255	1.087573	23485.249247	0.937414	0.691252	2.729613e+07	1.110572e+08
min	1930.000000	0.000000	0.000000	2000.000000	0.000000	0.000000	2.010000e+02	2.500000e+01
25%	1970.000000	1.000000	0.000000	30000.000000	0.000000	0.000000	2.620000e+02	1.188750e+03
50%	1990.000000	2.000000	1.000000	41579.500000	0.000000	0.000000	3.370000e+02	2.191000e+03
75%	2002.000000	3.000000	2.000000	61374.500000	1.000000	1.000000	2.497220e+05	4.395006e+07
max	2014.000000	10.000000	7.000000	173850.000000	6.000000	5.000000	9.741060e+07	3.001865e+08

Check out the Missing Values

In [ ]:
dataset.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64
dataset.shape


In [ ]:
dataset.shape
(4572, 20)

In [ ]:
4572/3720 *100

81.36482939632546

Method 1

In [ ]:
data =dataset.dropna(inplace=False)

In [ ]:
dataset.shape
(4572, 20)

In [ ]:
data.shape
(850, 20)

In [ ]:
data.isnull().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64
data.shape
(850, 20)

method2 fillna with mean, median, mode


In [ ]:
dataset['Year'].fillna(dataset['Year'].mean(),inplace=True)
dataset['Year'].fillna(dataset['Year'].median(),inplace=True)
dataset['Year'].fillna(dataset['Year'].mode(),inplace=True)
mean, median, mode.

method 3 dropping values

In [ ]:
dataset.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64
dataset.shape

In [ ]:
# drop the missing values
salary_dataset = salary_dataset.dropna(how='any')

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64
data.shape
(850, 20)